import type { Metadata } from "next";
import "./globals.css";

import Header from "@/shared/components/layouts/header";
import Footer from "@/shared/components/layouts/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning
        className="antialiased"
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
